name: create a comment on new issue 
on: 
  issues:
    types: [opened]

jobs:
    comment-with-action:
      runs-on: ubuntu-latest
      steps:
          - name: "The issue in my comment is"
            run: echo '${{ toJSON(github.event.issue) }}' | jq
            shell: bash
          - name: " To print our title of issue "
            run: echo "${{github.event.issue.title}}"
          - name: " To print our description of issue "
            run: echo "${{github.event.issue.body}}"
            
            
            
    
